version: 2
jobs:
  build:
    docker:
      - image: ubuntu:zesty
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: apt-get update -y && apt-get install libyaml-cpp-dev libsqlite3-dev util-linux librsvg2-dev libcairomm-1.0-dev libepoxy-dev libgtkmm-3.0-dev uuid-dev libboost-dev  libzmq5 libzmq3-dev libglm-dev libgit2-dev libcurl4-gnutls-dev -y
      - run:
          name: Build
          command: make -j2
